from django.shortcuts import render

def home(request): return render(request, 'main/home.html')
def org_profile(request): return render(request, 'main/about/org_profile.html')
def board_members(request): return render(request, 'main/about/board_members.html')
def exec_committee(request): return render(request, 'main/about/exec_committee.html')
def events_list(request): return render(request, 'main/activities/events_list.html')
def events_upcoming(request): return render(request, 'main/activities/events_upcoming.html')
def events_ongoing(request): return render(request, 'main/activities/events_ongoing.html')
def events_completed(request): return render(request, 'main/activities/events_completed.html')
def event_details(request): return render(request, 'main/activities/event_details.html')
def event_register(request): return render(request, 'main/activities/event_register.html')
def workshops_list(request): return render(request, 'main/activities/workshops_list.html')
def workshop_details(request): return render(request, 'main/activities/workshop_details.html')
def workshop_register(request): return render(request, 'main/activities/workshop_register.html')
def awareness_home(request): return render(request, 'main/activities/awareness_home.html')
def awareness_category(request, category): return render(request, 'main/activities/awareness_category.html')
def volunteer_home(request): return render(request, 'main/activities/volunteer_home.html')
def volunteer_category(request, category): return render(request, 'main/activities/volunteer_category.html')
def volunteer_details(request): return render(request, 'main/activities/volunteer_details.html')
def gallery_albums(request): return render(request, 'main/archive/gallery_albums.html')
def gallery_photos(request): return render(request, 'main/archive/gallery_photos.html')
def gallery_videos(request): return render(request, 'main/archive/gallery_videos.html')
def news_list(request): return render(request, 'main/archive/news_list.html')
def news_details(request): return render(request, 'main/archive/news_details.html')
def media_coverage(request): return render(request, 'main/archive/media_coverage.html')
def success_stories(request): return render(request, 'main/archive/success_stories.html')
def membership_home(request): return render(request, 'main/membership/membership_home.html')
def membership_student(request): return render(request, 'main/membership/membership_student.html')
def membership_general(request): return render(request, 'main/membership/membership_general.html')
def membership_lifetime(request): return render(request, 'main/membership/membership_lifetime.html')
def membership_register(request): return render(request, 'main/membership/membership_register.html')
def contact(request): return render(request, 'main/contact/contact.html')
def faq(request): return render(request, 'main/contact/faq.html')
def privacy_policy(request): return render(request, 'main/contact/privacy_policy.html')
def terms(request): return render(request, 'main/contact/terms.html')
def login(request): return render(request, 'main/auth/login.html')
def register(request): return render(request, 'main/auth/register.html')
def forgot_password(request): return render(request, 'main/auth/forgot_password.html')
def reset_password(request): return render(request, 'main/auth/reset_password.html')
def change_password(request): return render(request, 'main/auth/change_password.html')