from django.shortcuts import render

def dashboard(request): return render(request, 'admin_portal/dashboard.html')
def user_management(request): return render(request, 'admin_portal/user_management.html')
def volunteer_management(request): return render(request, 'admin_portal/volunteer_management.html')
def membership_management(request): return render(request, 'admin_portal/membership_management.html')
def event_management(request): return render(request, 'admin_portal/event_management.html')
def workshop_management(request): return render(request, 'admin_portal/workshop_management.html')
def activity_management(request): return render(request, 'admin_portal/activity_management.html')
def gallery_management(request): return render(request, 'admin_portal/gallery_management.html')
def news_management(request): return render(request, 'admin_portal/news_management.html')
def board_management(request): return render(request, 'admin_portal/board_management.html')
def committee_management(request): return render(request, 'admin_portal/committee_management.html')
def certificate_management(request): return render(request, 'admin_portal/certificate_management.html')
def reports(request): return render(request, 'admin_portal/reports.html')
def admin_notifications(request): return render(request, 'admin_portal/notifications.html')
def website_settings(request): return render(request, 'admin_portal/website_settings.html')
def audit_logs(request): return render(request, 'admin_portal/audit_logs.html')
def admin_profile(request): return render(request, 'admin_portal/profile.html')
def admin_change_password(request): return render(request, 'admin_portal/change_password.html')
def admin_login(request): return render(request, 'admin_portal/login.html')